timeout: 7200s

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/$PROJECT_ID/locations/us-central1/workerPools/${_PRIMARY_POOL}

substitutions:
  _PRIMARY_POOL: sonic-primary
  _AFFECTED_LABELS: //bazel/... //tools/... //sources/... //packages/... //images/... //platforms/... //installers/...

steps:
  - id: presubmit
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    env:
      - USE_BAZEL_VERSION=8.5.0
      - SONIC_AFFECTED_LABELS=${_AFFECTED_LABELS}
    args:
      - -lc
      - ./ci/gcp/presubmit.sh
