"""Assembles a SONiC ONIE installer (.bin) — self-extracting shell archive.

Mirrors the ``onie-mk-demo.sh`` logic from sonic-buildimage.  Packages
Docker image tarballs, rootfs .debs, platform configuration, and an install
script into a tar archive.  Prepends a self-extracting shell header with
SHA-1 integrity verification, producing a single ``.bin`` file suitable for
ONIE-based network-OS installation.

All inputs are hermetic Bazel targets — no Docker daemon or network access
is required during the build action.

Example:
    ```starlark
    load("//tools/onie:defs.bzl", "onie_installer")

    onie_installer(
        name = "sonic-vs",
        platform = "vs",
        machine = "vs",
        onie_platform = "x86_64-kvm_x86_64-r0",
        docker_images = [
            "//docker/database:docker-database_tarball",
        ],
    )
    ```
"""

# ─────────────────────────────────────────────────────────────────────────
# Build-script template.
#
# @@MARKERS@@ are replaced by Starlark string.replace() at analysis time.
# This avoids all conflicts with shell $, {}, and Python .format() syntax.
# ─────────────────────────────────────────────────────────────────────────

_BUILD_SCRIPT = """\
#!/usr/bin/env bash
set -euo pipefail
#
# SONiC ONIE installer assembler — generated by Bazel onie_installer() rule.
# Follows the onie-mk-demo.sh pattern from sonic-buildimage.
#

OUT_BIN="$1"

# ── Portable SHA-1 ──────────────────────────────────────────────────────
if command -v sha1sum >/dev/null 2>&1; then
    _sha1() { sha1sum "$1" | awk '{print $1}'; }
elif command -v shasum >/dev/null 2>&1; then
    _sha1() { shasum -a 1 "$1" | awk '{print $1}'; }
else
    echo "ERROR: no SHA-1 tool available" >&2
    exit 1
fi

# ── Staging ─────────────────────────────────────────────────────────────
STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT

INSTALLER_DIR="$STAGING/installer"
mkdir -p "$INSTALLER_DIR/payload/docker" \\
         "$INSTALLER_DIR/payload/rootfs" \\
         "$INSTALLER_DIR/payload/boot"

# ── install.sh (embedded in the installer archive) ──────────────────────
cat > "$INSTALLER_DIR/install.sh" <<'INSTALL_SCRIPT_EOF'
#!/bin/sh
# SONiC Installer — generated by Bazel onie_installer() rule
# Platform: @@PLATFORM@@  Machine: @@MACHINE@@  Version: @@IMAGE_VERSION@@
set -e

cd $(dirname $0)

# Read configuration files written by the installer assembler.
[ -r ./machine.conf ]    && . ./machine.conf
[ -r ./onie-image.conf ] && . ./onie-image.conf
[ -r ./platform.conf ]   && . ./platform.conf

echo "SONiC Network Operating System"
echo "=============================="
echo "  Platform : ${platform:-@@PLATFORM@@}"
echo "  Machine  : ${machine:-@@MACHINE@@}"
echo "  Version  : @@IMAGE_VERSION@@"
echo ""

# --- Payload inventory ---
if [ -d ./payload/docker ]; then
    echo "Docker images:"
    for f in ./payload/docker/*; do
        [ -f "$f" ] && echo "  $(basename "$f")"
    done
fi

if [ -d ./payload/rootfs ]; then
    echo "Root filesystem packages:"
    for f in ./payload/rootfs/*; do
        [ -f "$f" ] && echo "  $(basename "$f")"
    done
fi

# TODO: Full ONIE/SONiC installation logic (partitioning, rootfs
# extraction, Docker loading) will be added once the rootfs squashfs
# assembly is implemented in Bazel.
echo ""
echo "SONiC installer payload verified successfully."
INSTALL_SCRIPT_EOF
chmod +x "$INSTALLER_DIR/install.sh"

# ── onie-image.conf ─────────────────────────────────────────────────────
cat > "$INSTALLER_DIR/onie-image.conf" <<'ONIE_CONF_EOF'
## SONiC ONIE Image Configuration — generated by Bazel
ONIE_IMAGE_PART_SIZE=@@ONIE_IMAGE_PART_SIZE@@
TARGET_PLATFORM=x86_64
TARGET_MACHINE=@@MACHINE@@
ONIEIMAGE_VERSION=r0
FILESYSTEM_SQUASHFS=fs.squashfs
INSTALLER_PAYLOAD=payload
FILESYSTEM_DOCKERFS=dockerfs.tar.gz
DOCKERFS_DIR=docker
DOCKER_RAMFS_SIZE=3500M
OUTPUT_ONIE_IMAGE=sonic-@@MACHINE@@.bin
ONIE_CONF_EOF

# ── machine.conf ────────────────────────────────────────────────────────
cat > "$INSTALLER_DIR/machine.conf" <<'MACHINE_CONF_EOF'
machine=@@MACHINE@@
platform=@@ONIE_PLATFORM@@
MACHINE_CONF_EOF

# ── platform.conf ───────────────────────────────────────────────────────
@@PLATFORM_CONF_CMD@@

# ── Copy payload files ──────────────────────────────────────────────────
@@DOCKER_COPY@@
@@DEB_COPY@@
@@KERNEL_COPY@@
@@EXTRA_COPY@@

# Remove empty payload directories.
rmdir "$INSTALLER_DIR/payload/docker" 2>/dev/null || true
rmdir "$INSTALLER_DIR/payload/rootfs" 2>/dev/null || true
rmdir "$INSTALLER_DIR/payload/boot"   2>/dev/null || true
rmdir "$INSTALLER_DIR/payload"        2>/dev/null || true

# ── Create tar archive ──────────────────────────────────────────────────
SHARCH_TAR="$STAGING/sharch.tar"
tar cf "$SHARCH_TAR" -C "$STAGING" installer

# ── Compute SHA-1 and size ──────────────────────────────────────────────
PAYLOAD_SHA1=$(_sha1 "$SHARCH_TAR")
PAYLOAD_SIZE=$(wc -c < "$SHARCH_TAR" | tr -d ' ')

# ── Write self-extracting header (ONIE sharch format) ───────────────────
cat > "$STAGING/sharch_header.sh" <<'SHARCH_BODY_EOF'
#!/bin/sh
# SONiC ONIE installer — self-extracting archive
# Assembled by Bazel onie_installer() rule
#
# Based on ONIE sharch format.
# Copyright (C) 2013 Curt Brune <curt@cumulusnetworks.com>
# SPDX-License-Identifier: GPL-2.0

echo -n "Verifying image checksum ..."
payload_image_size=%%PAYLOAD_IMAGE_SIZE%%

sha1=$(sed -e '1,/^exit_marker$/d' "$0" | head -c $payload_image_size | sha1sum | awk '{ print $1 }')

payload_sha1=%%IMAGE_SHA1%%

if [ "$sha1" != "$payload_sha1" ] ; then
    echo
    echo "ERROR: Unable to verify archive checksum"
    echo "Expected: $payload_sha1"
    echo "Found   : $sha1"
    exit 1
fi

echo " OK."

cur_wd=$(pwd)
export cur_wd
archive_path=$(realpath "$0")
tmp_dir=$(mktemp -d)
cd $tmp_dir
echo -n "Preparing image archive ..."
sed -e '1,/^exit_marker$/d' $archive_path | head -c $payload_image_size | tar xf - || exit 1
echo " OK."
cd $cur_wd

if [ -n "${extract:-}" ] ; then
    echo "Image extracted to: $tmp_dir"
    exit 0
fi

$tmp_dir/installer/install.sh
rc="$?"

rm -rf $tmp_dir
exit $rc
exit_marker
SHARCH_BODY_EOF

# Substitute SHA-1 and payload size in the header.
# Uses temp file for portability (BSD sed -i differs from GNU).
TMPFILE="$STAGING/header.tmp"
sed -e "s/%%IMAGE_SHA1%%/$PAYLOAD_SHA1/" \\
    -e "s/%%PAYLOAD_IMAGE_SIZE%%/$PAYLOAD_SIZE/" \\
    "$STAGING/sharch_header.sh" > "$TMPFILE"
cat "$TMPFILE" > "$OUT_BIN"

# ── Append tar payload ──────────────────────────────────────────────────
cat "$SHARCH_TAR" >> "$OUT_BIN"
chmod +x "$OUT_BIN"

echo "Assembled ONIE installer: $(basename "$OUT_BIN") (payload: ${PAYLOAD_SIZE} bytes, sha1: ${PAYLOAD_SHA1})"
"""

def _onie_installer_impl(ctx):
    """Assembles a self-extracting ONIE installer binary."""
    out_bin = ctx.actions.declare_file(ctx.label.name + ".bin")

    # ── Compute derived values ───────────────────────────────────────────
    onie_platform = ctx.attr.onie_platform
    if not onie_platform:
        onie_platform = "x86_64-%s-r0" % ctx.attr.platform

    # ── Gather inputs ────────────────────────────────────────────────────
    all_inputs = []

    docker_files = []
    for img in ctx.attr.docker_images:
        for f in img[DefaultInfo].files.to_list():
            docker_files.append(f)
        all_inputs.append(img[DefaultInfo].files)

    deb_files = []
    for deb in ctx.attr.rootfs_debs:
        for f in deb[DefaultInfo].files.to_list():
            deb_files.append(f)
        all_inputs.append(deb[DefaultInfo].files)

    kernel_file = None
    if ctx.attr.kernel:
        for f in ctx.attr.kernel[DefaultInfo].files.to_list():
            kernel_file = f
            break
        all_inputs.append(ctx.attr.kernel[DefaultInfo].files)

    extra_entries = []  # list of (file, dest_path)
    for src, dest in ctx.attr.extra_files.items():
        for f in src[DefaultInfo].files.to_list():
            extra_entries.append((f, dest))
        all_inputs.append(src[DefaultInfo].files)

    platform_conf_file = None
    if ctx.attr.platform_conf:
        for f in ctx.attr.platform_conf[DefaultInfo].files.to_list():
            platform_conf_file = f
            break
        all_inputs.append(ctx.attr.platform_conf[DefaultInfo].files)

    inputs = depset(transitive = all_inputs)

    # ── Build shell snippets for payload copying ─────────────────────────
    docker_cmds = [
        'cp "%s" "$INSTALLER_DIR/payload/docker/"' % f.path
        for f in docker_files
    ]
    docker_copy = "\n".join(docker_cmds) if docker_cmds else "# (no docker images)"

    deb_cmds = [
        'cp "%s" "$INSTALLER_DIR/payload/rootfs/"' % f.path
        for f in deb_files
    ]
    deb_copy = "\n".join(deb_cmds) if deb_cmds else "# (no rootfs debs)"

    if kernel_file:
        kernel_copy = 'cp "%s" "$INSTALLER_DIR/payload/boot/"' % kernel_file.path
    else:
        kernel_copy = "# (no kernel)"

    extra_cmds = []
    for f, dest in extra_entries:
        extra_cmds.append(
            'mkdir -p "$(dirname "$INSTALLER_DIR/payload/%s")" && cp "%s" "$INSTALLER_DIR/payload/%s"' % (dest, f.path, dest),
        )
    extra_copy = "\n".join(extra_cmds) if extra_cmds else "# (no extra files)"

    if platform_conf_file:
        platform_conf_cmd = 'cp "%s" "$INSTALLER_DIR/platform.conf"' % platform_conf_file.path
    else:
        platform_conf_cmd = 'touch "$INSTALLER_DIR/platform.conf"'

    # ── Generate assembler script via @@MARKER@@ replacement ─────────────
    content = _BUILD_SCRIPT
    content = content.replace("@@PLATFORM@@", ctx.attr.platform)
    content = content.replace("@@MACHINE@@", ctx.attr.machine)
    content = content.replace("@@ONIE_PLATFORM@@", onie_platform)
    content = content.replace("@@IMAGE_VERSION@@", ctx.attr.image_version)
    content = content.replace("@@ONIE_IMAGE_PART_SIZE@@", str(ctx.attr.onie_image_part_size))
    content = content.replace("@@PLATFORM_CONF_CMD@@", platform_conf_cmd)
    content = content.replace("@@DOCKER_COPY@@", docker_copy)
    content = content.replace("@@DEB_COPY@@", deb_copy)
    content = content.replace("@@KERNEL_COPY@@", kernel_copy)
    content = content.replace("@@EXTRA_COPY@@", extra_copy)

    script = ctx.actions.declare_file(ctx.label.name + "_mk_installer.sh")
    ctx.actions.write(
        output = script,
        content = content,
        is_executable = True,
    )

    ctx.actions.run(
        inputs = inputs,
        tools = [script],
        outputs = [out_bin],
        executable = script,
        arguments = [out_bin.path],
        mnemonic = "OnieInstaller",
        progress_message = "Assembling ONIE installer %s (platform=%s)" % (
            ctx.label.name,
            ctx.attr.platform,
        ),
    )

    return [DefaultInfo(files = depset([out_bin]))]

onie_installer = rule(
    implementation = _onie_installer_impl,
    attrs = {
        "docker_images": attr.label_list(
            default = [],
            allow_files = True,
            doc = "OCI tarball labels (``oci_load`` targets) to bundle into the installer.",
        ),
        "extra_files": attr.label_keyed_string_dict(
            default = {},
            allow_files = True,
            doc = "Additional files to include: ``{source_label: installer_path}``.",
        ),
        "image_version": attr.string(
            default = "bazel-dev",
            doc = "Version string embedded in the installer (default: ``bazel-dev``).",
        ),
        "kernel": attr.label(
            mandatory = False,
            allow_files = True,
            doc = "Linux kernel image label.  Omit for container-only validation builds.",
        ),
        "machine": attr.string(
            default = "generic_x86",
            doc = "ONIE machine identifier (default: ``generic_x86``).",
        ),
        "onie_image_part_size": attr.int(
            default = 32768,
            doc = "ONIE partition size in MB (default: 32768 = 32 GB).",
        ),
        "onie_platform": attr.string(
            default = "",
            doc = "Full ONIE platform string (e.g. ``x86_64-kvm_x86_64-r0``). " +
                  "Defaults to ``x86_64-<platform>-r0``.",
        ),
        "platform": attr.string(
            mandatory = True,
            doc = "SONiC platform identifier (e.g. ``broadcom``, ``mellanox``, ``vs``).",
        ),
        "platform_conf": attr.label(
            mandatory = False,
            allow_single_file = True,
            doc = "Platform-specific configuration file (``platform.conf``). " +
                  "An empty file is created if omitted.",
        ),
        "rootfs_debs": attr.label_list(
            default = [],
            allow_files = [".deb"],
            doc = "``.deb`` package labels for the root filesystem.",
        ),
    },
    doc = "Assembles a SONiC ONIE installer ``.bin`` (self-extracting shell archive).",
)
